blank_issues_enabled: false
contact_links:
  - name: Read Before Reporting an Issue
    url: https://github.com/ostris/ai-toolkit/blob/main/.github/ISSUE_TEMPLATE/before_reporting.md
    about: Please read this important information before submitting an issue.